import { Event, SportTab } from './types'

export const sportTabs: SportTab[] = [
  { id: 'all', label: 'All', count: 17 },
  { id: 'football', label: 'Football', count: 4 },
  { id: 'ufc', label: 'UFC', count: 3 },
  { id: 'nba', label: 'NBA', count: 5 },
  { id: 'nfl', label: 'NFL', count: 3 },
  { id: 'boxing', label: 'Boxing', count: 2 },
]

export interface NewsItem {
  id: string
  title: string
  summary: string
  source: string
  sport: string
  timestamp: string
  impact: 'high' | 'medium' | 'low'
  tag: string
}

export const sportsNews: NewsItem[] = [
  {
    id: 'news-1',
    title: 'Makhachev confirms weight cut on track for UFC 310',
    summary: 'Islam Makhachev posted a training video showing sharp cardio work. Team reports no issues with the weight cut to 155 lbs ahead of his title defense.',
    source: 'ESPN MMA',
    sport: 'ufc',
    timestamp: '2h ago',
    impact: 'high',
    tag: 'Injury Report',
  },
  {
    id: 'news-2',
    title: 'Celtics starting lineup confirmed for Game 5',
    summary: 'Kristaps Porzingis cleared to play after knee soreness. Full strength lineup expected for the elimination game at TD Garden.',
    source: 'The Athletic',
    sport: 'nba',
    timestamp: '45m ago',
    impact: 'high',
    tag: 'Lineup News',
  },
  {
    id: 'news-3',
    title: 'Arsenal set to rest Saka for Premier League clash',
    summary: 'Bukayo Saka likely to start from the bench against Manchester City due to fatigue management. Trossard expected to fill in on the right wing.',
    source: 'Sky Sports',
    sport: 'football',
    timestamp: '1h ago',
    impact: 'high',
    tag: 'Team News',
  },
  {
    id: 'news-4',
    title: 'Mahomes knee brace spotted in pregame warmups',
    summary: 'Patrick Mahomes was seen wearing a protective knee brace during pregame drills. Chiefs downplay the concern as precautionary.',
    source: 'NFL Network',
    sport: 'nfl',
    timestamp: '3h ago',
    impact: 'medium',
    tag: 'Injury Report',
  },
  {
    id: 'news-5',
    title: 'Fury camp changes sparring partners late in camp',
    summary: 'Tyson Fury has brought in two new southpaw sparring partners to simulate Joshua style. Camp insider reports Fury in best shape since Wilder trilogy.',
    source: 'Boxing Scene',
    sport: 'boxing',
    timestamp: '5h ago',
    impact: 'medium',
    tag: 'Training Camp',
  },
  {
    id: 'news-6',
    title: 'Line movement: Sharp money flooding Celtics -4.5',
    summary: 'Over 72% of sharp handle now on Celtics spread. Line has moved from -3.5 to -4.5 since open. Reverse line movement signals professional action.',
    source: 'Action Network',
    sport: 'nba',
    timestamp: '30m ago',
    impact: 'high',
    tag: 'Line Movement',
  },
]

export const sampleEvents: Event[] = [
  // UFC Events
  {
    id: 'ufc-1',
    sport: 'ufc',
    league: 'UFC 310 - Main Card',
    startTime: '2026-06-15T22:00:00Z',
    status: 'upcoming',
    participant1: {
      id: 'p1',
      name: 'Islam Makhachev',
      shortName: 'Makhachev',
      logo: '',
      record: '26-1-0',
      stats: { reach: 70.5, height: 70, strikingAcc: 59, tdAcc: 62, strikesPerMin: 4.2, tdDefense: 88 },
    },
    participant2: {
      id: 'p2',
      name: 'Charles Oliveira',
      shortName: 'Oliveira',
      logo: '',
      record: '34-10-0',
      stats: { reach: 74, height: 70, strikingAcc: 53, tdAcc: 42, strikesPerMin: 3.5, tdDefense: 60 },
    },
    odds: { home: 1.45, away: 2.85 },
    aiConfidence: 87,
    badges: ['value', 'hot'],
    valueBets: [
      {
        market: 'Makhachev by Decision',
        currentOdds: 2.80,
        trueProbability: 45,
        expectedValue: 11.3,
        edge: 9.4,
        confidence: 'high',
        reasoning: 'Makhachev has won 5 of his last 7 by decision. Oliveira has elite defensive grappling making a finish less likely. Our model heavily favors a grinding decision win.',
        suggestedStake: '$55 (5.5% Kelly)',
      },
    ],
  },
  {
    id: 'ufc-2',
    sport: 'ufc',
    league: 'UFC 310 - Co-Main',
    startTime: '2026-06-15T21:00:00Z',
    status: 'upcoming',
    participant1: {
      id: 'p3',
      name: 'Dustin Poirier',
      shortName: 'Poirier',
      logo: '',
      record: '29-8-0',
      stats: { reach: 72, height: 69, strikingAcc: 52, tdAcc: 36, strikesPerMin: 5.8, tdDefense: 72 },
    },
    participant2: {
      id: 'p4',
      name: 'Justin Gaethje',
      shortName: 'Gaethje',
      logo: '',
      record: '24-4-0',
      stats: { reach: 70, height: 69, strikingAcc: 55, tdAcc: 100, strikesPerMin: 7.6, tdDefense: 74 },
    },
    odds: { home: 2.10, away: 1.75 },
    aiConfidence: 72,
    badges: ['hot', 'sharp'],
    valueBets: [
      {
        market: 'Poirier by KO/TKO',
        currentOdds: 4.50,
        trueProbability: 28,
        expectedValue: 8.2,
        edge: 6.1,
        confidence: 'medium',
        reasoning: 'Poirier has devastating power and Gaethje has been stopped before. The high volume striking matchup increases KO probability significantly.',
        suggestedStake: '$35 (3.5% Kelly)',
      },
    ],
  },
  {
    id: 'ufc-3',
    sport: 'ufc',
    league: 'UFC 310 - Main Card',
    startTime: '2026-06-15T20:00:00Z',
    status: 'live',
    participant1: {
      id: 'p5',
      name: 'Sean Strickland',
      shortName: 'Strickland',
      logo: '',
      record: '28-6-0',
      stats: { reach: 76, height: 73, strikingAcc: 48, tdAcc: 44, strikesPerMin: 6.1, tdDefense: 82 },
    },
    participant2: {
      id: 'p6',
      name: 'Dricus Du Plessis',
      shortName: 'Du Plessis',
      logo: '',
      record: '21-2-0',
      stats: { reach: 76, height: 73, strikingAcc: 58, tdAcc: 50, strikesPerMin: 5.8, tdDefense: 68 },
    },
    odds: { home: 2.25, away: 1.65 },
    aiConfidence: 65,
    badges: ['live', 'hot'],
  },
  // NBA Events
  {
    id: 'nba-1',
    sport: 'nba',
    league: 'NBA Finals - Game 5',
    startTime: '2026-06-16T01:00:00Z',
    status: 'upcoming',
    participant1: {
      id: 'n1',
      name: 'Boston Celtics',
      shortName: 'BOS',
      logo: '',
      form: ['W', 'W', 'L', 'W', 'W'],
      stats: { ortg: 118.2, drtg: 108.5, pace: 99.2, threePt: 38.1 },
    },
    participant2: {
      id: 'n2',
      name: 'Oklahoma City Thunder',
      shortName: 'OKC',
      logo: '',
      form: ['W', 'L', 'W', 'L', 'W'],
      stats: { ortg: 116.8, drtg: 109.2, pace: 100.1, threePt: 36.5 },
    },
    odds: { home: 1.65, away: 2.30, spread: { line: -4.5, homeOdds: 1.91, awayOdds: 1.91 }, total: { line: 218.5, over: 1.91, under: 1.91 } },
    aiConfidence: 78,
    badges: ['value', 'sharp'],
    valueBets: [
      {
        market: 'Celtics -4.5',
        currentOdds: 1.91,
        trueProbability: 58,
        expectedValue: 6.8,
        edge: 5.2,
        confidence: 'high',
        reasoning: 'Home-court advantage in elimination games boosts Celtics to a 58% cover rate. Their defense ranks top-3 in half-court efficiency this postseason.',
        suggestedStake: '$60 (6% Kelly)',
      },
    ],
  },
  {
    id: 'nba-2',
    sport: 'nba',
    league: 'NBA Finals - Game 5',
    startTime: '2026-06-16T01:00:00Z',
    status: 'upcoming',
    participant1: {
      id: 'n3',
      name: 'Denver Nuggets',
      shortName: 'DEN',
      logo: '',
      form: ['W', 'W', 'W', 'L', 'L'],
      stats: { ortg: 115.5, drtg: 110.8, pace: 97.8, threePt: 35.2 },
    },
    participant2: {
      id: 'n4',
      name: 'Minnesota Timberwolves',
      shortName: 'MIN',
      logo: '',
      form: ['L', 'W', 'W', 'W', 'L'],
      stats: { ortg: 113.2, drtg: 106.9, pace: 96.5, threePt: 34.8 },
    },
    odds: { home: 1.85, away: 2.00, spread: { line: -2.5, homeOdds: 1.91, awayOdds: 1.91 }, total: { line: 211.5, over: 1.91, under: 1.91 } },
    aiConfidence: 62,
    badges: ['sharp'],
  },
  {
    id: 'nba-3',
    sport: 'nba',
    league: 'NBA Playoffs',
    startTime: '2026-06-15T23:30:00Z',
    status: 'live',
    participant1: {
      id: 'n5',
      name: 'Los Angeles Lakers',
      shortName: 'LAL',
      logo: '',
      form: ['W', 'L', 'W', 'W', 'L'],
      stats: { ortg: 114.1, drtg: 111.5, pace: 99.9, threePt: 33.5 },
    },
    participant2: {
      id: 'n6',
      name: 'Golden State Warriors',
      shortName: 'GSW',
      logo: '',
      form: ['W', 'W', 'L', 'W', 'W'],
      stats: { ortg: 115.9, drtg: 110.1, pace: 100.8, threePt: 37.9 },
    },
    odds: { home: 2.15, away: 1.72, spread: { line: 3.5, homeOdds: 1.91, awayOdds: 1.91 }, total: { line: 225.5, over: 1.91, under: 1.91 } },
    aiConfidence: 58,
    badges: ['live'],
  },
  {
    id: 'nba-4',
    sport: 'nba',
    league: 'NBA Playoffs',
    startTime: '2026-06-17T01:00:00Z',
    status: 'upcoming',
    participant1: {
      id: 'n7',
      name: 'Milwaukee Bucks',
      shortName: 'MIL',
      logo: '',
      form: ['W', 'W', 'W', 'L', 'W'],
      stats: { ortg: 116.4, drtg: 109.8, pace: 98.2, threePt: 36.1 },
    },
    participant2: {
      id: 'n8',
      name: 'Philadelphia 76ers',
      shortName: 'PHI',
      logo: '',
      form: ['L', 'W', 'L', 'W', 'W'],
      stats: { ortg: 114.8, drtg: 110.5, pace: 97.5, threePt: 35.7 },
    },
    odds: { home: 1.55, away: 2.55, spread: { line: -5.5, homeOdds: 1.91, awayOdds: 1.91 }, total: { line: 223.5, over: 1.91, under: 1.91 } },
    aiConfidence: 74,
    badges: ['value'],
  },
  {
    id: 'nba-5',
    sport: 'nba',
    league: 'NBA Playoffs',
    startTime: '2026-06-17T23:30:00Z',
    status: 'upcoming',
    participant1: {
      id: 'n9',
      name: 'Dallas Mavericks',
      shortName: 'DAL',
      logo: '',
      form: ['W', 'L', 'W', 'L', 'W'],
      stats: { ortg: 117.1, drtg: 111.2, pace: 99.5, threePt: 37.3 },
    },
    participant2: {
      id: 'n10',
      name: 'Phoenix Suns',
      shortName: 'PHX',
      logo: '',
      form: ['W', 'W', 'L', 'L', 'W'],
      stats: { ortg: 115.3, drtg: 110.8, pace: 98.8, threePt: 35.9 },
    },
    odds: { home: 1.75, away: 2.15, spread: { line: -3.5, homeOdds: 1.91, awayOdds: 1.91 }, total: { line: 228.5, over: 1.91, under: 1.91 } },
    aiConfidence: 69,
    badges: ['sharp'],
  },
  // NFL Events
  {
    id: 'nfl-1',
    sport: 'nfl',
    league: 'NFL Week 12',
    startTime: '2026-06-15T18:00:00Z',
    status: 'upcoming',
    participant1: {
      id: 'f1',
      name: 'Kansas City Chiefs',
      shortName: 'KC',
      logo: '',
      form: ['W', 'W', 'W', 'L', 'W'],
      stats: { dvoa: 22.5 },
    },
    participant2: {
      id: 'f2',
      name: 'Buffalo Bills',
      shortName: 'BUF',
      logo: '',
      form: ['W', 'L', 'W', 'W', 'W'],
      stats: { dvoa: 19.8 },
    },
    odds: { home: 1.80, draw: 15.00, away: 2.05, spread: { line: -2.5, homeOdds: 1.91, awayOdds: 1.91 }, total: { line: 49.5, over: 1.91, under: 1.91 } },
    aiConfidence: 71,
    badges: ['hot', 'sharp'],
  },
  {
    id: 'nfl-2',
    sport: 'nfl',
    league: 'NFL Week 12',
    startTime: '2026-06-15T21:25:00Z',
    status: 'upcoming',
    participant1: {
      id: 'f3',
      name: 'San Francisco 49ers',
      shortName: 'SF',
      logo: '',
      form: ['W', 'W', 'L', 'W', 'L'],
      stats: { dvoa: 18.3 },
    },
    participant2: {
      id: 'f4',
      name: 'Dallas Cowboys',
      shortName: 'DAL',
      logo: '',
      form: ['L', 'W', 'W', 'L', 'W'],
      stats: { dvoa: 12.1 },
    },
    odds: { home: 1.55, draw: 18.00, away: 2.60, spread: { line: -6.5, homeOdds: 1.91, awayOdds: 1.91 }, total: { line: 46.5, over: 1.91, under: 1.91 } },
    aiConfidence: 79,
    badges: ['value'],
  },
  {
    id: 'nfl-3',
    sport: 'nfl',
    league: 'NFL Week 12 - SNF',
    startTime: '2026-06-16T00:20:00Z',
    status: 'upcoming',
    participant1: {
      id: 'f5',
      name: 'Philadelphia Eagles',
      shortName: 'PHI',
      logo: '',
      form: ['W', 'W', 'W', 'W', 'L'],
      stats: { dvoa: 20.1 },
    },
    participant2: {
      id: 'f6',
      name: 'Miami Dolphins',
      shortName: 'MIA',
      logo: '',
      form: ['W', 'L', 'W', 'W', 'W'],
      stats: { dvoa: 15.6 },
    },
    odds: { home: 1.70, draw: 16.00, away: 2.25, spread: { line: -3.5, homeOdds: 1.91, awayOdds: 1.91 }, total: { line: 51.5, over: 1.91, under: 1.91 } },
    aiConfidence: 75,
    badges: ['sharp'],
  },
  // Football (Soccer) Events
  {
    id: 'fb-1',
    sport: 'football',
    league: 'Premier League',
    startTime: '2026-06-15T15:00:00Z',
    status: 'upcoming',
    participant1: {
      id: 's1',
      name: 'Arsenal',
      shortName: 'ARS',
      logo: '',
      form: ['W', 'W', 'D', 'W', 'W'],
    },
    participant2: {
      id: 's2',
      name: 'Manchester City',
      shortName: 'MCI',
      logo: '',
      form: ['W', 'L', 'W', 'W', 'D'],
    },
    odds: { home: 2.30, draw: 3.40, away: 2.90 },
    aiConfidence: 82,
    badges: ['value', 'hot'],
    valueBets: [
      {
        market: 'Arsenal Win',
        currentOdds: 2.30,
        trueProbability: 48,
        expectedValue: 10.4,
        edge: 8.6,
        confidence: 'high',
        reasoning: 'Arsenal at the Emirates have won 11 of their last 12 home matches. City missing key midfield options reduces their away threat significantly.',
        suggestedStake: '$50 (5% Kelly)',
      },
    ],
  },
  {
    id: 'fb-2',
    sport: 'football',
    league: 'Champions League - Semi Final',
    startTime: '2026-06-15T19:00:00Z',
    status: 'upcoming',
    participant1: {
      id: 's3',
      name: 'Real Madrid',
      shortName: 'RMA',
      logo: '',
      form: ['W', 'W', 'W', 'D', 'W'],
    },
    participant2: {
      id: 's4',
      name: 'Bayern Munich',
      shortName: 'BAY',
      logo: '',
      form: ['W', 'W', 'L', 'W', 'W'],
    },
    odds: { home: 2.10, draw: 3.50, away: 3.20 },
    aiConfidence: 76,
    badges: ['hot'],
  },
  {
    id: 'fb-3',
    sport: 'football',
    league: 'Premier League',
    startTime: '2026-06-16T14:00:00Z',
    status: 'upcoming',
    participant1: {
      id: 's5',
      name: 'Liverpool',
      shortName: 'LIV',
      logo: '',
      form: ['W', 'W', 'W', 'L', 'W'],
    },
    participant2: {
      id: 's6',
      name: 'Chelsea',
      shortName: 'CHE',
      logo: '',
      form: ['D', 'W', 'L', 'W', 'W'],
    },
    odds: { home: 1.75, draw: 3.80, away: 4.20 },
    aiConfidence: 80,
    badges: ['value'],
  },
  {
    id: 'fb-4',
    sport: 'football',
    league: 'Champions League - Semi Final',
    startTime: '2026-06-16T19:00:00Z',
    status: 'upcoming',
    participant1: {
      id: 's7',
      name: 'Paris Saint-Germain',
      shortName: 'PSG',
      logo: '',
      form: ['W', 'D', 'W', 'W', 'W'],
    },
    participant2: {
      id: 's8',
      name: 'Inter Milan',
      shortName: 'INT',
      logo: '',
      form: ['W', 'W', 'W', 'D', 'L'],
    },
    odds: { home: 1.90, draw: 3.60, away: 3.80 },
    aiConfidence: 68,
    badges: ['sharp'],
  },
  // Boxing Events
  {
    id: 'box-1',
    sport: 'boxing',
    league: 'WBC Heavyweight Title',
    startTime: '2026-06-22T03:00:00Z',
    status: 'upcoming',
    participant1: {
      id: 'b1',
      name: 'Tyson Fury',
      shortName: 'Fury',
      logo: '',
      record: '34-1-1',
      stats: { reach: 85, height: 78 },
    },
    participant2: {
      id: 'b2',
      name: 'Anthony Joshua',
      shortName: 'Joshua',
      logo: '',
      record: '28-4-0',
      stats: { reach: 82, height: 78 },
    },
    odds: { home: 1.60, away: 2.40 },
    aiConfidence: 73,
    badges: ['hot'],
  },
  {
    id: 'box-2',
    sport: 'boxing',
    league: 'WBA Super Middleweight',
    startTime: '2026-06-22T02:00:00Z',
    status: 'upcoming',
    participant1: {
      id: 'b3',
      name: 'Canelo Alvarez',
      shortName: 'Canelo',
      logo: '',
      record: '61-2-2',
      stats: { reach: 70.5, height: 68 },
    },
    participant2: {
      id: 'b4',
      name: 'David Benavidez',
      shortName: 'Benavidez',
      logo: '',
      record: '29-0-0',
      stats: { reach: 75, height: 73 },
    },
    odds: { home: 2.20, away: 1.70 },
    aiConfidence: 64,
    badges: ['value', 'sharp'],
  },
]
